### ISSUE TITLE
Creacion del UsuarioFormBean y ProductoFormBean

### ISSUE THREAD

**Issue by SofiaGDelgado** [FerMart17/Heladeria#2]
@BrendaMendez17 Falta la creacion de un paquete nuevo aplicacion.form.bean. Y tambien la creacion de UsuarioFormBean y ProductoFormBean

**Comment by BrendaMendez17** [comment]
@SofiaGDelgado no inche pue ura

**Comment by SofiaGDelgado** [comment]
Vamo a desaprobar ura 😠

**Comment by BrendaMendez17** [comment]
Cállate ura 🙄 capa y llegamos ?😲

**Comment by SofiaGDelgado** [comment]
😝 solo hace el formbean gil

**Comment by BrendaMendez17** [comment]
@SofiaGDelgado eso no es muy taki taki rumba de tu parte :c

**Comment by SofiaGDelgado** [comment]
😐
